spring:
    datasource:
        url: jdbc:mysql://awseb-e-viz8m3b7gt-stack-awsebrdsdatabase-hku8btvopfgt.czjwb8ct2nn4.ap-northeast-2.rds.amazonaws.com:3306/board?useSSL=false&serverTimezone=Asia/Seoul
        username: fastcam
        password: fastcam1234
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true
                default_batch_fetch_size: 100
            dialect: org.hibernate.dialect.MySQL8Dialect
    cache:
        type: redis
        redis:
            host: fc-board-redis-0001-001.4bjhyh.0001.apn2.cache.amazonaws.com
            port: 6379
